name: MineFinancial
main: reolina.MineFinancial.main.MineFinancial
version: 0.1.0
api-version: 1.17
authors: [Reolight, Eva]
commands:
  bank:
    description: Info about bank
    usage:
      /<command> balance - check the balance
      /<command> emission (value) - emit new amount of money
    aliases: [банк]
  player:
    description: Player financial role promotion
    usage:
      /<command> balance - check player balance
      /<command> finrole - check player FRole
    aliases: [игрок]
  finrole:
    description: Promoting player role in finance system
    usage:
      /<command> [promote|demote] [player] - promotion/demotion
    aliases: [финроль]
  clan:
    description: for clan management
    usage:
      /<command> list - список кланов
      /<command> balance - проверка баланса клана
      /<command> join (ClanName) - примоединение к клану (или запрос)
      /<command> leave - leave current clan
      /<command> explell (Player) - expell player (leader only)
      /<command> invite (Player) - inviting player in clan (leader only)

      /<command> [get|set] leader (clan) - get/set leader name of current player clan (or indicated in clauses)
      /<command> [promote|demote] player - promote or demote player
      /<command> message <message> - clan chat;
    aliases: [клан]
  rem:
    description: for reply on requiests & showing notifications
    usage:
      /<command> [ID] [y|n] - reply on requiest
      /<command> - list of requires (not implemented yet)
    aliases: [reminder]
  pay:
    description: for payment or trade
    usage:
      /<command> [#toClan|@toPlayer|$toBank] amount - pay to instance
      /<command> [@RelevantClan] [#toClan|@toPlayer|$toBank] amount - pay from clan to instance
    aliases: [transaction]
  market:
    description: market menu
    usage:
      /<command> - show GUI
      /<command> sell - sell item
    aliases: [рынок]
  credit:
    description: allows player borrow money and be a creditor
    usage:
      /<command> create (amount) (rate?) (days?) - создаёт кредит на сумму amount ставкой rate на дней days
      /<command> create asClan (amount) (rate?) (days?) - создаёт кредит от имени клана на сумму amount ставкой rate на дней days
      /<command> take (ID) (amount?) - взять кредит ID на сумму amount
      /<command> pay (ID) (amount) - оплатить кредит